// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystem.Infrastructure.Context;

#nullable disable

namespace TicketingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            EventDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "My awesome Venue",
                            Title = "Updated Rock Concert"
                        });
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174040"),
                            CartId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            PriceId = new Guid("00000000-0000-0000-0000-000000000000"),
                            SeatId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Status = "Booked",
                            UserId = new Guid("123e4567-e89b-12d3-a456-426614174000"),
                            Version = 0
                        });
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174060"),
                            OrderId = new Guid("123e4567-e89b-12d3-a456-426614174040"),
                            PaymentDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SectionId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174030"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = false,
                            Row = "B",
                            SeatNumber = "3",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174031"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = false,
                            Row = "B",
                            SeatNumber = "4",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = true,
                            Row = "A",
                            SeatNumber = "1",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = true,
                            Row = "A",
                            SeatNumber = "2",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = true,
                            Row = "A",
                            SeatNumber = "3",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = true,
                            Row = "A",
                            SeatNumber = "4",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = true,
                            Row = "A",
                            SeatNumber = "5",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = true,
                            Row = "A",
                            SeatNumber = "6",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = true,
                            Row = "A",
                            SeatNumber = "7",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            EventId = new Guid("123e4567-e89b-12d3-a456-426614174020"),
                            IsAvailable = true,
                            Row = "A",
                            SeatNumber = "8",
                            SectionId = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Status = "Available",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174011"),
                            Name = "Updated Section A",
                            VenueId = new Guid("bb578f5f-836d-4767-8e98-58d0afbc3ff8")
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174012"),
                            Name = "Updated Section B",
                            VenueId = new Guid("bb578f5f-836d-4767-8e98-58d0afbc3ff8")
                        });
                });

            modelBuilder.Entity("TicketingSystem.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174000"),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174001"),
                            DateOfBirth = new DateTime(1992, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "0987654321"
                        });
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426614174050"),
                            Amount = 150.00m,
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = new Guid("123e4567-e89b-12d3-a456-426614174040"),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("UserSeatReservation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "SeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("UserSeatReservations");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("123e4567-e89b-12d3-a456-426614174000"),
                            SeatId = new Guid("123e4567-e89b-12d3-a456-426614174030"),
                            ExpiresAt = new DateTime(2025, 6, 1, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReservedAt = new DateTime(2025, 6, 1, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = new Guid("123e4567-e89b-12d3-a456-426614174001"),
                            SeatId = new Guid("123e4567-e89b-12d3-a456-426614174031"),
                            ExpiresAt = new DateTime(2025, 6, 2, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReservedAt = new DateTime(2025, 6, 2, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb578f5f-836d-4767-8e98-58d0afbc3ff8"),
                            Address = "Centralna Street 57",
                            Name = "My awesome Venue"
                        });
                });

            modelBuilder.Entity("Seat", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany("Seats")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Section", "Section")
                        .WithMany("Seats")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Section", b =>
                {
                    b.HasOne("Venue", "Venue")
                        .WithMany("Sections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("UserSeatReservation", b =>
                {
                    b.HasOne("Seat", "Seat")
                        .WithMany("SeatReservations")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystem.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Seat", b =>
                {
                    b.Navigation("SeatReservations");
                });

            modelBuilder.Entity("Section", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Venue", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
